services:
  web:
    build: .
    ports:
      - "8282:8282"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: unless-stopped
